# Generated by Django 3.0.5 on 2022-04-20 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('danhmuc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sanpham',
            fields=[
                ('sanpham_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sl', models.IntegerField(null=True)),
                ('image', models.ImageField(default=None, upload_to='images')),
                ('price', models.CharField(max_length=20)),
                ('danhmuc_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='danhmuc.danhmuc')),
            ],
        ),
    ]
